name: GuidedDiff
channels:
  - main
  - r
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.5.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.17
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.1
  - pandas=2.2.1
  - pcre2=10.42
  - pillow=10.2.0
  - pip=23.3.1
  - ply=3.11
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - qt-main=5.15.2
  - readline=8.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.65.0
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - annotated-types==0.6.0
      - anyio==4.3.0
      - appdirs==1.4.4
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - exceptiongroup==1.2.0
      - fastprogress==1.0.3
      - filelock==3.13.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.6
      - jinja2==3.1.3
      - joblib==1.4.0
      - lightning-utilities==0.11.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.19.0
      - opencv-python==4.9.0.80
      - progressbar==2.5
      - protobuf==4.25.3
      - psutil==5.9.8
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - python-dotenv==1.0.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - sentry-sdk==1.42.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sniffio==1.3.1
      - sympy==1.12
      - threadpoolctl==3.4.0
      - torch==2.2.1
      - torchmetrics==1.3.2
      - torchvision==0.17.1
      - triton==2.2.0
      - typing-extensions==4.10.0
      - urllib3==2.2.1
      - wandb==0.16.4
